# matrix testings
name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-latest, macOS-latest, windows-latest]
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Cabel Update
        run: |
          cabal v3-update
          cabal v3-freeze $CONFIG
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - name: Build Site
        run: |
          cabal v3-build $CONFIG
          cabal exec site build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch